# Generated by Django 5.2.5 on 2025-08-21 15:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyGeo',
            fields=[
                ('acct', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'property_geo',
            },
        ),
        migrations.CreateModel(
            name='RealAcct',
            fields=[
                ('acct', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('site_addr_1', models.CharField(blank=True, max_length=255, null=True)),
                ('site_addr_3', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'real_acct',
            },
        ),
    ]
